[build]
  command = "yarn build && yarn export"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[redirects]]
  from = "/leaderboard/*"
  to = "/leaderboard/[guildId].html"
  status = 200

[[redirects]]
  from = "https://2.sushii.xyz/*"
  to = "https://sushii.xyz/:splat"
  status = 301
  force = true
