[build]
  command = "yarn build && yarn export"


[[plugins]]
# package = "@netlify/plugin-nextjs"
  package = "netlify-plugin-cache-nextjs"

[[redirects]]
  from = "/leaderboard/*"
  to = "/leaderboard/[guildId].html"
  status = 200
