name: Docker

on:
    push:
        tags:
            - "sushii-web-v*"

env:
    IMAGE_NAME: ghcr.io/sushiibot/sushii-web

jobs:
    push:
        name: Build and publish Docker Image
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - uses: actions/checkout@v2

            - name: Docker meta
              id: docker_meta
              uses: crazy-max/ghaction-docker-meta@v1
              with:
                  images: ${{ env.IMAGE_NAME }}
                  tag-match: "v(.*)"
                  tag-match-group: "1"
                  tag-sha: true

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Cache Docker layers
              uses: actions/cache@v2
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-

            - name: Login to Github Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.CR_PAT }}

            - name: Build and push image to GitHub Packages
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache-new
                  tags: ${{ steps.docker_meta.outputs.tags }}
                  labels: ${{ steps.docker_meta.outputs.labels }}
            # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
            # Temp fix
            # https://github.com/docker/build-push-action/issues/252
            # https://github.com/moby/buildkit/issues/1896
            - name: Move cache
              run: |
                  rm -rf /tmp/.buildx-cache
                  mv /tmp/.buildx-cache-new /tmp/.buildx-cache
